version: '3'

services:
  mongo-primary:
    image: mongo
    container_name: mongo-primary
    ports:
      - "27017:27017"
    networks:
      - mongodb-cluster
    command: "--replSet rs0"

  mongo-secondary1:
    image: mongo
    container_name: mongo-secondary1
    ports:
      - "27018:27017"
    networks:
      - mongodb-cluster
    command: "--replSet rs0"

  mongo-secondary2:
    image: mongo
    container_name: mongo-secondary2
    ports:
      - "27019:27017"
    networks:
      - mongodb-cluster
    command: "--replSet rs0"

networks:
  mongodb-cluster:
    driver: bridge